from autogen_agentchat.agents import AssistantAgent
from autogen_core.model_context import BufferedChatCompletionContext


def create_reflection_agent(model_client):

    reflection = AssistantAgent(
        name="reflection_agent",

        system_message="""
You are a Reflection Agent.

Your job:
Improve the answers generated by worker agents.

Responsibilities:
- Combine worker outputs
- Improve clarity
- Remove redundancy
- Produce a refined response
""",

        model_client=model_client,
        model_context=BufferedChatCompletionContext(buffer_size=10)
    )

    return reflection