
server {
    listen 80;
    server_name practice.local;
    return 301 https://$host$request_uri;
}


server {
    listen 443 ssl;
    server_name practice.local;

    ssl_certificate /etc/nginx/certs/practice.local.pem;
    ssl_certificate_key /etc/nginx/certs/practice.local-key.pem;

    location / {
        proxy_pass http://server:5000;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-Proto https;
    }
}
